uploads = []
generated = []

[[outputs]]
id = "nG42daxEn3-jWmD4nnype"
uri = "file://gsol-token-logo-512.png"
type = "image"
title = "GSOL Token Logo 512×512"

[[outputs]]
id = "X3eAAFKN5XWSKi2csX2Dp"
uri = "file://gsol-512x512.png"
type = "image"
title = "GSOL Token Logo - 512×512"
